@startuml
class book {
    +id: long
    +ISBN: string
    +nameBook: string
    +author: string
    +price: bigDecimal

    +totalQantity: int
    +descriotion: string
    +status: bookStatus

    +createAt: LocalDateTime
    +updateAt: LocalDateTime
}
class Author {
    +id: long
    +name: int
    +biography: string
    +email: string
    +phone: string
    +createAt: LocalDateTime
    +updateAt: LocalDateTime
}
class Reader {
    +id: int
    user: string
    password: string
    +fullname: string
    +email: string
    +phone: string
    +createAt: LocalDateTime
    +updateAt: LocalDateTime
}
class publisher {
    +id: long
    +name: string
    +email: string
    +phone: string
    +address: string
}
class Staff {
    +id: int
    +name: string
    +email: string
    +phone: string
    +salary: float

}
class BorrowSlip {
 +id: long
 +borrowDay: localDate
 +dueDate: localDate
 +return: localDate
 +status: borrowStatus
 +note: string

}


class borrowDetail {
 +id: long
 +quantity: int
 +borrowCondition: string
 +returnCondition: string
 +fineAmount: string
 +note: string
}
@enduml