@startuml
class book {
    +id: long
    +ISBN: string
    +nameBook: string
    +descriotion: string
    +author: string
    +price: bigDecimal
    +totalQantity: int
    +status: bookStatus

    +createAt: LocalDateTime
    +updateAt: LocalDateTime
}
class Author {
    +id: long
    +name: int
    +biography: string
    +email: string
    +phone: string
    +createAt: LocalDateTime
    +updateAt: LocalDateTime
}
class Reader {
    +id: int
    user: string
    password: string
    +fullname: string
    +email: string
    +phone: string
    createAt: LocalDateTime
    UpdateAt: LocalDateTime
}
class publisher {
    +id: int
    +name: string
    +email: string
    +phone: string
    +address: string
}
class Staff {
    +id: int
    +name: string
    +email: string
    +phone: string
    +salary: float

}
class BorrowSlip {
 +idReader: int
 +idBook: int
 +browingDay: Date
}

class regulations {
    +regulations: list
    +nameregualtion:string
}

class return {

}
@enduml